### ISSUE TITLE
get_owned_games() function not being called when gog galaxy starts for some integrations 

### ISSUE THREAD

**Issue by Pab10Suarez** [gogcom/galaxy-integrations-python-api#180]
**Problem**
integrations from emulators that use this function to make games appear as installed don't get installed games

**Solution**
Call the function at the beginning or provide an alternative

**Comment by mbanczerowski** [comment]
Hi @Pab10Suarez 

the problem is known. It should be fixed in upcoming release.

**Comment by Pab10Suarez** [comment]
Heya just checking up the new update, so for now i have seen that retroarch integrations are fixed now, but dolphin and gamecube are not (have not looked in this last ones) so there's still a problem but is a big fix (for my use) i'll look in detail soon

**Comment by mbanczerowski** [comment]
@Pab10Suarez thanks for sharing the outcome. Actually the logic shouldn't be plugin-platform-wise now. If you could redirect me to those plugins' repositories or share plugin and GalaxyClient logs - that would be helpful for further investigation.

**Comment by Pab10Suarez** [comment]
for now i've only used wii and ncube and saw this problem, i think it also happens with others plugins for example cemu/wiiu plug in 
[logs ncube wii problem.zip](https://github.com/gogcom/galaxy-integrations-python-api/files/6983989/logs.ncube.wii.problem.zip)

**Comment by mbanczerowski** [comment]
Thanks @Pab10Suarez, could you also attach `GalaxyClient.log`?

**Comment by Pab10Suarez** [comment]
> Thanks @Pab10Suarez, could you also attach `GalaxyClient.log`?

it is there, i didn't put in in the file name sorry

**Comment by mbanczerowski** [comment]
Ok, I think we're on track. There is non-obvious flow regarding to authorization state. Started to working on refactor for that.

**Comment by Pab10Suarez** [comment]
> Ok, I think we're on track. There is non-obvious flow regarding to authorization state. Started to working on refactor for that.

thx! i think it's very important

**Comment by Pab10Suarez** [comment]
Heya last update fixed wii and gamecube error for me probably fixed others plataforms but i'll need to verify thx!
